import type { EngineInput } from './types';

export const USER_NAME = 'Sanket';

// "Established user" — matches the approved design numbers exactly:
// income 65,000 − bills 21,116 − goal 5,000 − buffer 6,000 = 32,884 remaining,
// ÷ 12 days left = ₹2,740 safe-to-spend today.
export const establishedInput: EngineInput = {
  today: '2026-07-20',
  daysTrackedWithApp: 97,
  bills: [
    {
      id: 'rent',
      name: 'Rent',
      shortLabel: 'Rent',
      // Already charged this cycle (lastRenewedDate) — next charge is next month,
      // so this correctly does NOT show up as "due this week" below.
      amount: 15000,
      dueDate: '2026-08-01',
      category: 'housing',
      monthsObserved: 4,
      lastRenewedDate: '2026-07-01',
    },
    {
      id: 'electricity',
      name: 'Bijli ka bill',
      shortLabel: 'Bijli',
      amount: 1420,
      dueDate: '2026-07-21',
      category: 'utility',
      monthsObserved: 3,
      lastRenewedDate: '2026-06-21',
    },
    {
      id: 'netflix',
      name: 'Netflix',
      shortLabel: 'Netflix',
      amount: 649,
      dueDate: '2026-08-17',
      category: 'subscription',
      monthsObserved: 3,
      lastRenewedDate: '2026-07-17',
      icon: '📺',
      cancelUrl: 'https://www.netflix.com/youraccount',
    },
    {
      id: 'spotify',
      name: 'Spotify',
      shortLabel: 'Spotify',
      amount: 119,
      dueDate: '2026-08-18',
      category: 'subscription',
      monthsObserved: 3,
      lastRenewedDate: '2026-07-18',
      icon: '🎵',
      cancelUrl: 'https://www.spotify.com/account/subscription/',
    },
    {
      id: 'hotstar',
      name: 'Hotstar',
      shortLabel: 'Hotstar',
      amount: 299,
      dueDate: '2026-08-16',
      category: 'subscription',
      monthsObserved: 3,
      lastRenewedDate: '2026-07-16',
      icon: '🎬',
      cancelUrl: 'https://www.hotstar.com/in/subscription',
    },
    {
      id: 'phone-wifi',
      name: 'Mobile + WiFi',
      shortLabel: 'Phone',
      amount: 3629,
      dueDate: '2026-07-25',
      category: 'telecom',
      monthsObserved: 3,
      lastRenewedDate: '2026-06-25',
    },
  ],
  billsAreEstimate: false,
  emergencyBuffer: 6000,
  goals: [
    {
      id: 'goa-trip',
      emoji: '🏖',
      name: 'Goa trip',
      targetAmount: 40000,
      savedAmount: 15000,
      monthlyContribution: 5000,
      deadlineDate: '2027-01-15',
    },
    {
      id: 'emergency-fund',
      emoji: '🛟',
      name: 'Emergency fund',
      targetAmount: 100000,
      savedAmount: 48000,
      monthlyContribution: 6000,
      deadlineDate: '2027-04-20',
    },
    {
      id: 'iphone',
      emoji: '📱',
      name: 'iPhone',
      targetAmount: 80000,
      savedAmount: 9000,
      monthlyContribution: 3000,
      deadlineDate: '2026-11-20',
    },
  ],
  transactionsTrackedCount: 23,
  cashTrackingEnabled: false,
  upiFullyCategorized: false,
  daysRemainingInMonth: 12,
  transactions: [
    {
      id: 'tx-salary',
      merchant: 'Salary — Employer Ltd',
      amount: 65000,
      date: '2026-07-01',
      type: 'credit',
    },
    {
      id: 'tx-1',
      merchant: 'Swiggy',
      amount: 380,
      date: '2026-07-20',
      type: 'debit',
    },
    {
      id: 'tx-2',
      merchant: 'HP Petrol Pump',
      amount: 1200,
      date: '2026-07-20',
      type: 'debit',
    },
    {
      id: 'tx-3',
      merchant: 'Netflix',
      amount: 649,
      date: '2026-07-20',
      type: 'debit',
    },
    {
      id: 'tx-4',
      merchant: 'UPI · Rahul ko',
      amount: 500,
      date: '2026-07-19',
      type: 'debit',
    },
    {
      id: 'tx-5',
      merchant: 'BigBasket',
      amount: 1840,
      date: '2026-07-19',
      type: 'debit',
    },
  ],
  categoryBudgets: [
    { id: 'food', category: 'Food', emoji: '🍔', budgeted: 8000, spent: 8900, previousMonthSpent: 7542 },
    { id: 'transport', category: 'Transport', emoji: '⛽', budgeted: 5000, spent: 3600, previousMonthSpent: 3400 },
    { id: 'shopping', category: 'Shopping', emoji: '🛍', budgeted: 4000, spent: 2100, previousMonthSpent: 2000 },
    { id: 'groceries', category: 'Groceries', emoji: '🛒', budgeted: 4000, spent: 3640, previousMonthSpent: 3500 },
  ],
};

// Day-1 cold start — only 4 days of data. Bills are unconfirmed estimates, no goals set
// yet, budgets haven't accumulated enough history, confidence is honestly "growing."
// Nothing here is fabricated: the ₹15,000 rent line and ₹18,800 reserve are explicitly
// flagged as estimates in the UI.
export const day1Input: EngineInput = {
  today: '2026-07-20',
  daysTrackedWithApp: 4,
  bills: [
    {
      id: 'rent-estimate',
      name: 'Rent (estimate)',
      shortLabel: 'Rent',
      amount: 15000,
      dueDate: '',
      category: 'housing',
      monthsObserved: 0,
      lastRenewedDate: '2026-07-01',
    },
  ],
  billsAreEstimate: true,
  emergencyBuffer: 18800,
  goals: [],
  transactionsTrackedCount: 6,
  cashTrackingEnabled: false,
  upiFullyCategorized: false,
  daysRemainingInMonth: 12,
  transactions: [
    {
      id: 'd1-tx-salary',
      merchant: 'Salary — Employer Ltd',
      amount: 65000,
      date: '2026-07-01',
      type: 'credit',
    },
    {
      id: 'd1-tx-1',
      merchant: 'Zomato',
      amount: 450,
      date: '2026-07-19',
      type: 'debit',
    },
    {
      id: 'd1-tx-2',
      merchant: 'IOCL Petrol Pump',
      amount: 220,
      date: '2026-07-18',
      type: 'debit',
    },
    {
      id: 'd1-tx-3',
      merchant: 'Amazon',
      amount: 1200,
      date: '2026-07-17',
      type: 'debit',
    },
  ],
  categoryBudgets: [],
};
